### ISSUE TITLE
Basic Image data fetch from Image APIs

### ISSUE THREAD

**Issue by dirkzukunft** [dirkzukunft/perfectpic#1]
## User Story
As a user, I want to search for images on Unsplash, Pexels, and Pixabay using a query, so that I get a mixed, weighted result.

## Acceptance criteria

Feature: Get image list based on query
- Scenario: Enter a keyword to search
  - When I search for an image described by a query
Then I get a list of image links
coming from the providers Unsplash, Pexels and Pixabay
ordered by a weight based on the number of results of each provider
containing only relevant data I need for further processing

## Tasks
- [x] fetch results from the 3 external APIs synchronously
- [x] weight and order them by result count
- [x] filter out relevant data: image link, thumbnail, author, source, source link, aspect ratio, max resolution, upload date, taken date
- [x] return an object usable for the frontend

## Blocked by
#2 

## Size
M
