### ISSUE TITLE
Page Search

### ISSUE THREAD

**Issue by dirkzukunft** [dirkzukunft/perfectpic#15]
## User Story
As a user, I want to be able to search and filter for stock photos.

## Design
[Link](https://www.figma.com/file/L4dBE9w4Hc6a6e6PLQiNC9/Perfect-Pic?node-id=2%3A3)

## Acceptance criteria

Feature: Search page
- Scenario: Initial call of the Search page
  -  When I am calling /search
Then I see a page with an input field to enter my search query
And to submit it by pressing Enter or click the input submit button

- Scenario: Result page
  -  When I have submitted the search
Then I see a result page with images, filter besides the search input on the top

## Tasks
- [ ] show search input with submit button
- [ ] show the results of the search below and the number of results
- [ ] show the navbar

## Blocked by
--
#8 
#13 

## Size
M
